import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";
import Hero from "../homePageUIComponents/Hero/Hero";
import Cases from "../homePageUIComponents/Cases/Cases";
import Skills from "../homePageUIComponents/Skills/Skills";
import Experience from "../homePageUIComponents/Experience/Experience";

export default function Home() {
  return (
    <div className="page">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Header />
      <main className="main">
        <Hero />
        <Cases />
        <Skills />
        <Experience />
      </main>
      <Footer />
    </div>
  );
}
